<a href="https://colab.research.google.com/github/S123AMAR/samar_pratap_data_science_and_visualisation_lab/blob/main/Samar_Pratap_3_PANDAS_SERIES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas series

Section A

In [ ]:
from pandas import Series
import pandas as pd

In [ ]:
sales = pd.Series([120,150,180,210])
sales

0    120
1    150
2    180
3    210
dtype: int64

In [ ]:
marks = pd.Series([72,81,69,90])
marks.values

array([72, 81, 69, 90])

In [ ]:
marks.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
temperature = pd.Series(
[28,31,30,29],
index=['Mon','tue','Wed','thu']
)
temperature

Mon    28
tue    31
Wed    30
thu    29
dtype: int64

In [ ]:
population = pd.Series(
    [35, 42, 31],
    index = ['Delhi','Mumbai','Jaipur']
)
population

Delhi     35
Mumbai    42
Jaipur    31
dtype: int64

In [ ]:
score = pd.Series([35,68,44,79,52])
score[score>50]

1    68
3    79
4    52
dtype: int64

In [ ]:
import pandas as pd

In [ ]:
import pandas as pd
subjects = pd.Series(
    [76, 83, 91],
           index = ['Physics','Chemistry','Maths']
                     )
print('Chemistry' in subjects.index)

True

In [ ]:
import pandas as pd
s = pd.Series(
    [10, 20, 30],
    index=['A','B','C']
)
print(s.to_dict())

{'A': 10, 'B': 20, 'C': 30}

In [ ]:
prices = {
    'pen': 10,
    'Notebook': 55,
    'Bag': 700
}
prices_series = pd.Series(prices)
prices_series

pen          10
Notebook     55
Bag         700
dtype: int64

In [ ]:
print("Dictionary heys become the series index.")

Dictionary heys become the series index.

In [ ]:
data = {
    'A': 10,
    'B': 20,
    'C': 30
}
s = Series(data, index=['A','B','C','D'])
s

A    10.0
B    20.0
C    30.0
D     NaN
dtype: float64

In [ ]:
pd.isnull(s)

In [ ]:

print(s.notnull())

In [ ]:
sales = pd.Series(
    [1000, 1500, 2000],
    index = ['January', 'February','March']
)
sales.name = 'Monthly sales'
print(sales)

In [ ]:
sales.index.name = 'Month'
print(sales)

Section B

In [ ]:
s =pd.Series([18, 45, 27,61],
             index=['  P','Q','R','S']
             )
print(s[s>30])

In [ ]:
s = pd.Series([500, 600, 700],
              index=['East', 'West', 'North']
              )
print('West' in s)
print(500 is s)

In [ ]:
city_data = {
    'Delhi': 80,
    'Pune': 65,
    'Kochi': 70
}
s = pd.Series(city_data,
              index=['Delhi', 'Pune', 'Chennai'])
print(s)

In [ ]:
s = pd.Series(
    {'W': 5, 'X': 10, 'Y': 15},
    index=['X', 'Y', 'Z', 'W']
)
print(pd.isnull(s))

X    False
Y    False
Z     True
W    False
dtype: bool

In [ ]:
s = pd.Series(
    {'W': 5, 'X': 10, 'Y': 15},
    index=['X', 'Y', 'Z', 'W']
)
print(pd.notnull(s))

X     True
Y     True
Z    False
W     True
dtype: bool

In [ ]:
s1 = pd.Series([10, 20, 30],
               index=['A','B','C'])
s2 = pd.Series([1, 2, 3],
               index=['C', 'A', 'B'])
print(s1 + s2)

A    12
B    23
C    31
dtype: int64

In [ ]:
s1 = pd.Series({'A': 12, 'B': 18})
s2 = pd.Series({'B': 5, 'C': 9 })
print(s1 + s2)

A     NaN
B    23.0
C     NaN
dtype: float64

In [ ]:
stock = pd.Series(
    [25, 40, 18],
    index=['Item1', 'Item2', 'Item3'],
)
stock_dict = stock.to_dict()
stock2 = pd.Series(stock_dict)
print(stock2)
print(stock_dict)

Item1    25
Item2    40
Item3    18
dtype: int64
{'Item1': 25, 'Item2': 40, 'Item3': 18}

In [ ]:
marks  ={
    'Maths': 88,
    'Science': 74,
    'English': 69,
    'History': 81
}
s = pd.Series(marks,
              index=['History', 'Maths', 'Science', 'English'])
print(s[s>70])

History    81
Maths      88
Science    74
dtype: int64

In [ ]:
rev = pd.Series([2000,3000,4000],
index=['Jan','Feb','Mar'])
rev.name = 'Revenue'
rev.index.name = 'Branch'
rev

Branch
Jan    2000
Feb    3000
Mar    4000
Name: Revenue, dtype: int64

Section C - HARD

In [ ]:
import pandas as pd
north = pd.Series({'Jan': 40, 'Feb': 55,'Mar': 60})
south= pd.Series({'Feb': 20,'Mar':25, 'Apr': 30})

total= north + south
print(total)

Apr     NaN
Feb    75.0
Jan     NaN
Mar    85.0
dtype: float64

In [ ]:
import pandas as pd
d = {'Red': 12,'Blue':18, 'Green': 24}
labels = ['Green', 'Red', 'Yellow', 'Blue']

result = pd.Series(d, index=labels)
print(result)
print(pd.isnull(result))

Green     24.0
Red       12.0
Yellow     NaN
Blue      18.0
dtype: float64
Green     False
Red       False
Yellow     True
Blue      False
dtype: bool

In [ ]:
import pandas as pd
s = pd.Series([90, 75,82],index=['Ravi','Aman', 'Neha'])
d = s.to_dict()
s2 = pd.Series(d)
print("Original Series:")
print(s)
print("\nDictionary:")
print(d)

print("\nNew Series:")
print(s2)

Original Series:
Ravi    90
Aman    75
Neha    82
dtype: int64

Dictionary:
{'Ravi': 90, 'Aman': 75, 'Neha': 82}

New Series:
Ravi    90
Aman    75
Neha    82
dtype: int64

In [ ]:
import pandas as pd

sales = pd.Series({
    'Laptop': 800,
    'Mobile': 450,
    'Tablet': 650,
    'Keyboard': 300
})
print("Sales Values:")
print(sales.values)

print("\nIndex:")
print(sales.index)
print("\nLaptop Sales:")
print(sales['Laptop'])
print("\nSales Above 500:")
print(sales[sales > 500])
print("\nIs Mobile Present?")
print('Mobile' in sales.index)


print("\nDictionary:")
print(sales.to_dict())

Sales Values:
[800 450 650 300]

Index:
Index(['Laptop', 'Mobile', 'Tablet', 'Keyboard'], dtype='object')

Laptop Sales:
800

Sales Above 500:
Laptop    800
Tablet    650
dtype: int64

Is Mobile Present?
True

Dictionary:
{'Laptop': 800, 'Mobile': 450, 'Tablet': 650, 'Keyboard': 300}

In [ ]:
import pandas as pd

data = {'A': 15,'B': 35,'C': 25}
s = pd.Series(data, index=['C', 'A','D', 'B'])
s.name = 'Observations'
s.index.name = 'Category'
print(s)
print("\nBoolean Filter:")
print(s[s > 20])
print("\nNot Null:")
print(pd.notnull(s))

Category
C    25.0
A    15.0
D     NaN
B    35.0
Name: Observations, dtype: float64

Boolean Filter:
Category
C    25.0
B    35.0
Name: Observations, dtype: float64

Not Null:
Category
C     True
A     True
D    False
B     True
Name: Observations, dtype: bool